# Generated by Django 5.0 on 2023-12-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус полного скана')),
                ('domains', models.TextField(verbose_name='Домены')),
                ('time_start', models.TimeField(auto_now=True)),
                ('time_end', models.TimeField()),
            ],
        ),
    ]
