# Generated by Django 5.0 on 2023-12-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullscan',
            options={'verbose_name': 'Скан', 'verbose_name_plural': 'Сканы'},
        ),
        migrations.AlterField(
            model_name='fullscan',
            name='status',
            field=models.CharField(default='Новый', max_length=50, verbose_name='Статус полного скана'),
        ),
        migrations.AlterField(
            model_name='fullscan',
            name='time_end',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fullscan',
            name='time_start',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
