# Generated by Django 5.0 on 2023-12-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_fullscan_options_alter_fullscan_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleiScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=250, verbose_name='Домен')),
                ('status', models.CharField(max_length=50, verbose_name='Статус полного скана')),
                ('full_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fullscan')),
            ],
        ),
    ]
