# Generated by Django 5.0 on 2023-12-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_nucleiscan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nucleiscan',
            options={'verbose_name': 'Nuclei скан', 'verbose_name_plural': 'Сканы nuclei'},
        ),
        migrations.RenameField(
            model_name='nucleiscan',
            old_name='domain',
            new_name='domains',
        ),
        migrations.AlterField(
            model_name='nucleiscan',
            name='status',
            field=models.CharField(max_length=150, verbose_name='Статус скана Nuclei'),
        ),
        migrations.CreateModel(
            name='NucleiTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(verbose_name='Правило')),
                ('description', models.TextField(verbose_name='Правило')),
                ('status', models.CharField(max_length=150, verbose_name='Статус триажа')),
                ('severity', models.CharField(max_length=50, verbose_name='Критичность')),
                ('domain', models.CharField(max_length=250, verbose_name='Домен')),
                ('NucleiScan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nucleiscan')),
            ],
            options={
                'verbose_name': 'Срабатывание nuclei',
                'verbose_name_plural': 'Срабатывания nuclei',
            },
        ),
    ]
