# Generated by Django 5.0 on 2023-12-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_nucleiscan_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nucleiscan',
            old_name='domains',
            new_name='domain',
        ),
    ]
