# Generated by Django 5.0 on 2023-12-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_domains_nucleiscan_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleitrigger',
            name='description',
            field=models.TextField(default=' ', verbose_name='Правило'),
        ),
        migrations.AlterField(
            model_name='nucleitrigger',
            name='domain',
            field=models.CharField(default=' ', max_length=250, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='nucleitrigger',
            name='rule',
            field=models.TextField(default=' ', verbose_name='Правило'),
        ),
        migrations.AlterField(
            model_name='nucleitrigger',
            name='severity',
            field=models.CharField(default=' ', max_length=50, verbose_name='Критичность'),
        ),
        migrations.AlterField(
            model_name='nucleitrigger',
            name='status',
            field=models.CharField(default=' ', max_length=150, verbose_name='Статус триажа'),
        ),
    ]
