# Generated by Django 5.0 on 2023-12-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_nucleitrigger_description_crawlscan_har'),
    ]

    operations = [
        migrations.AddField(
            model_name='har',
            name='type',
            field=models.CharField(default='Пасивный', max_length=250, verbose_name='Тип'),
        ),
    ]
