# Generated by Django 5.0 on 2023-12-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_zapscan_zaptrigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zapscan',
            options={'verbose_name': 'Zap Scan', 'verbose_name_plural': 'Zap Scans'},
        ),
        migrations.AlterModelOptions(
            name='zaptrigger',
            options={'verbose_name': 'Срабатывание ZAP', 'verbose_name_plural': 'Срабатывания ZAP'},
        ),
        migrations.AddField(
            model_name='zaptrigger',
            name='instance_attack',
            field=models.TextField(default=' ', verbose_name='Атака'),
        ),
        migrations.AddField(
            model_name='zaptrigger',
            name='instance_evidence',
            field=models.TextField(default=' ', verbose_name='PoC'),
        ),
        migrations.AddField(
            model_name='zaptrigger',
            name='instance_metod',
            field=models.TextField(default='GET', verbose_name='Метод'),
        ),
        migrations.AddField(
            model_name='zaptrigger',
            name='instance_otherinfo',
            field=models.TextField(default=' ', verbose_name='Доп информация'),
        ),
        migrations.AddField(
            model_name='zaptrigger',
            name='instance_param',
            field=models.TextField(default=' ', verbose_name='Параметры'),
        ),
        migrations.AddField(
            model_name='zaptrigger',
            name='riskdesc',
            field=models.TextField(default='информативный', verbose_name='Уровень'),
        ),
    ]
