# Generated by Django 5.0 on 2023-12-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_zapscan_options_alter_zaptrigger_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaptrigger',
            name='instance_url',
            field=models.TextField(default=' ', verbose_name='URL'),
        ),
    ]
