# Generated by Django 5.0 on 2023-12-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_zaptrigger_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Zap_Trigger',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=' ', null=True, verbose_name='Комментарий'),
        ),
    ]
