# Generated by Django 5.0 on 2023-12-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_comment_zap_trigger_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleitrigger',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comment'),
        ),
    ]
